version: "3"
services:
  web:
    build: .
    depends_on:
      - mysql
      - mailhog
    ports:
      - "3405:80"
    volumes:
      - .:/var/www/html
  mysql:
    image: mysql:8.0
    ports:
      - "3406:3306"
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=root
  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "1025:1025"
      - "9082:8025"
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_lilou_book
    restart: always
    ports:
      - 3407:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mysql
